lcviz/__init__.py
lcviz/conftest.py
lcviz/tests/test_translator.py
lcviz/utils.py

This PR has an implementation for a `glue-astronomy`-style translator from `lightkurve.LightCurve` objects to `glue.core.Data` objects. The contents of the `lcviz/utils.py` file will ultimately go into a PR to `glue-astronomy`, but I'm putting them here for now, so we don't have to wait on upstream releases to work here. 
My assigned ticket was to actually parse Kepler FITS files, which will be trivial after this first-step PR is merged, since those features are implemented in lightkurve. In the soon-to-come follow-up PR, I'll implement something like a `lightkurve_parser` which uses lightkurve's [`read` function](https://docs.lightkurve.org/reference/io.html) to construct a `LightCurve` from a Kepler or TESS data product, and rely on the translator in this PR to send the contents into …

Translator for lightkurve.LightCurve objects to glue Data objs

---

docs/index.rst
docs/reference/api.rst
lcviz/helper.py
lcviz/viewers.py

Sphinx was producing an error that it couldn't find api docs that don't exist. This PR implements basic API docs and the necessary skeleton to render properly. Thanks to Pey-Lian for the `__all__` heads up!

Implement basic API doc skeleton

---

lcviz/viewers.py

This PR "fixes" (in a really hacky way) some missing methods that we need from jdaviz's spectrum viewer that are not available in the `JdavizViewerMixin` mixin that `TimeProfileView` inherits.  We don't want to inherit directly from `SpecvizProfileView`, because that comes with a lot of spectrum-specific methods that we don't want here.  Ideally, we should refactor this on the jdaviz-end to pull these shared methods into a separate mixin which can then be used from lcviz.

jdaviz spectrum viewer inheritance

---

README.rst

I've chosen the color of the jdaviz label to be the darker-blue jdaviz logo color `#355973` used on the `Jda` part of the logo. We could also choose the lighter one `#336699` used in the `viz` part.
*Update*: I've opted for the lighter blue now.

Add jdaviz badge to readme

---

lcviz/conftest.py
lcviz/helper.py
lcviz/tests/test_parser.py
lcviz/utils.py
lcviz/viewers.py

This PR gets time subsets working for LCviz. [🐱](https://jira.stsci.edu/browse/JDAT-3297)
https://user-images.githubusercontent.com/3497584/234955643-55aeb31c-5a7e-4283-94a1-0fbc1bbd7ca9.mov
Covered in this PR:
* Added a Kepler/TESS quality flag component to the translated `LightCurve`s (will later useful for masking)
* adapted the `LightCurve` translator in lcviz to enable subset selections from light curves
* Made a new glue `Coordinates` subclass to use for the time axis (analog of glue-astro’s `SpectralCoordinates`)
* Added translators for the `KeplerLightCurve` and `TessLightCurve` subclasses of `LightCurve` (so the type of the input `*LightCurve` object is preserved on round-trip)
This PR depends on upstream updates to jdaviz as of https://github.com/spacetelescope/jdaviz/pull/2168, …

Adding support for subsets in time

---

lcviz/__init__.py
lcviz/helper.py
lcviz/parsers.py
lcviz/plugins/__init__.py
lcviz/plugins/plot_options/__init__.py
lcviz/plugins/plot_options/plot_options.py
lcviz/state.py
lcviz/tests/test_parser.py
lcviz/tools.py
lcviz/viewers.py
notebooks/LCvizExample.ipynb

This PR swaps out the ProfileViewer with ScatterViewer so that we can view the light curve as markers instead of lines and eventually have different arrays along the x-axis (for phase-viewer support).
This also overrides the `user_api` for the plot options plugin, but requires https://github.com/spacetelescope/jdaviz/pull/2193 in order to have access to the necessary glue-state objects and UI for those entries in the plugin itself.  This can be tested against that PR, but will eventually need a bump in the version of jdaviz once that PR is finalized/released.  If for some reason the decision is made to not merge that into jdaviz, the plot options logic can be added to lcviz as a follow-up PR.
With the exception of plot options, everything else should work with jdaviz main.

support for markers instead of lines via ScatterViewer

---

lcviz/viewers.py

This PR enables a vertical/y-range zoom tool in the light curve viewers, and requires https://github.com/spacetelescope/jdaviz/pull/2206 (merged in main, but currently unreleased)

enable yrangezoom

---

lcviz/tests/test_parser.py
pyproject.toml

This PR sets the min version requirement for jdaviz to 3.5+ and will hopefully fix most/all of the CI failures 🤞

require jdaviz 3.5+

---

lcviz/helper.py

This PR will be needed if https://github.com/spacetelescope/jdaviz/pull/2199 and ~https://github.com/javerbukh/jdaviz/pull/15~ https://github.com/spacetelescope/jdaviz/pull/2214 are adopted upstream to support temporal subsets.

update for upstream changes to get_data

---

lcviz/utils.py

introduced by [mouseover coordinates](https://github.com/spacetelescope/lcviz/pull/22) trying to access `viewer.data()[0].flux.unit`

fix bug that raised traceback when creating subsets

---

lcviz/tests/test_parser.py

~currently~ originally expected to fail for subset plugin changes in jdaviz, but should be fixed by https://github.com/spacetelescope/jdaviz/pull/2256

add test coverage for yrange roi

---

lcviz/helper.py
lcviz/parsers.py
lcviz/plugins/coords_info/coords_info.py
lcviz/plugins/ephemeris/ephemeris.py
lcviz/plugins/flatten/flatten.py
lcviz/state.py
lcviz/utils.py
lcviz/viewers.py
notebooks/LCvizExample.ipynb

This PR adds support for loading multiple data entries into one LCviz instance. Changes required included:
* properly managing the "reference time" of the first loaded data
* consistent linking between temporal axes across time/phase viewers
* using consistent glue `ComponentID`s for time components in the LightCurve translator and in the Ephemeris plugin
* overriding the `viewer.state.reset_limits` method for light curves
* refactoring the `TimeCoordinate` class, which acts as the WCS-like coordinate object for light curves
I also updated the example notebook with Ephemeris and Flatten use cases with two quarters of the HAT-P-11 Kepler light curve.
glue-jupyter's bqplot interface has a `density_map` feature which renders a 2D histogram of datapoints when there are many datapoints in a …

Load multiple data with different start times

---

lcviz/plugins/ephemeris/ephemeris.py
notebooks/LCvizExample.ipynb

Fix for phase axis `ComponentID`s that restores ephemeris support. [🐱](https://jira.stsci.edu/browse/JDAT-3690).

Fix for ephemeris phase axis

---

lcviz/helper.py

This PR requires https://github.com/spacetelescope/jdaviz/pull/2392 and will set the "help" button in the main app toolbar to point to lcviz's read the docs, instead of jdaviz's.

set link for read the docs

---

lcviz/helper.py
lcviz/parsers.py
lcviz/plugins/ephemeris/ephemeris.py
lcviz/plugins/flatten/flatten.py
lcviz/state.py
lcviz/tests/test_parser.py
lcviz/tests/test_plugin_ephemeris.py
lcviz/tests/test_plugin_flatten.py
lcviz/tests/test_viewers.py
lcviz/utils.py

This PR increases overall test coverage from 85.65% to 92.95% (and simplifies some logic in the light curve parser).
NOTE: uncovered lines in `events.py` and `template_mixin.py` are scheduled to be moved upstream by #35 and #36, respectively, which should then increase percent coverage even further.

increase test coverage

---

lcviz/plugins/coords_info/coords_info.py

glue-jupyter made changes to the ScatterLayerState - this PR updates lcviz to be able to handle glue-jupyter before _and_ after this change.

update for changes in glue-jupyter 0.18

---

.readthedocs.yaml
docs/conf.py
docs/index.rst
docs/installation.rst
docs/plugins.rst
docs/reference/api.rst
docs/reference/api_plugins.rst
lcviz/plugins/frequency_analysis/frequency_analysis.py
lcviz/tests/test_plugin_ephemeris.py
lcviz/tests/test_plugin_flatten.py
lcviz/tests/test_plugin_frequency_analysis.py
lcviz/tests/test_plugin_markers.py
lcviz/tests/test_plugin_metadata.py
lcviz/tests/test_plugin_plot_options.py
pyproject.toml

This PR:
* updates the docs theme to use the same as jdaviz
* adds information on the index page briefly explaining lcviz and linking to jdaviz and lightkurve
* copies (relevant) installation information from jdaviz
* exposes API docs for plugins
* links from each plugin to jdaviz/lightkurve, when applicable
* provides user-API snippets for each of the plugins
This does not intend to be a comprehensive/final update to the docs, but just to get in shape for an initial release.  Areas that could still use improvement include:
* add lcviz logo (once created)
* screenshots/recording on splash page
* extended descriptions for each plugin
* development docs (anything that is lcviz-specific, otherwise point to jdaviz docs)
[rendered docs](https://lcviz--46.org.readthedocs.build/en/46/)

DOC: update documentation

---

lcviz/plugins/ephemeris/ephemeris.py
lcviz/plugins/ephemeris/ephemeris.vue
lcviz/state.py
lcviz/tests/test_plugin_ephemeris.py
lcviz/viewers.py
notebooks/LCvizExample.ipynb

This PR implements a "phase_wrap" option in the ephemeris plugin along with automatic phase-limits updates ~a convenient in-plugin identification when the phase-wrapped data falls outside the viewer x-limits~. 
<details>
<summary>original in-plugin limits warning</summary>
**NOTE**: hint text for the wrapping UI element has been updated slightly since this recording to say "Phased data will encompass the range (1-wrap_at, wrap_at)"
https://github.com/spacetelescope/lcviz/assets/877591/19a8f6e8-2882-4d5a-b0bb-3de8e642fa2a
</details>
<details open>
<summary>auto-updating phase-limits</summary>
https://github.com/spacetelescope/lcviz/assets/877591/a012a3e5-f633-4608-8ff7-1e30fe6b15cb
</details>

ephemeris plugin: custom phase-wrapping

---

docs/plugins.rst
docs/reference/api_plugins.rst
lcviz/components/plugin_ephemeris_select.vue
lcviz/events.py
lcviz/helper.py
lcviz/marks.py
lcviz/plugins/__init__.py
lcviz/plugins/binning/__init__.py
lcviz/plugins/binning/binning.py
lcviz/plugins/binning/binning.vue
lcviz/plugins/coords_info/coords_info.py
lcviz/plugins/ephemeris/ephemeris.py
lcviz/plugins/flatten/flatten.py
lcviz/plugins/frequency_analysis/frequency_analysis.py
lcviz/template_mixin.py
lcviz/tests/test_plugin_binning.py
lcviz/tests/test_plugin_ephemeris.py
lcviz/utils.py
lcviz/viewers.py

This PR implements a binning plugin (wrapping existing `lightkurve` binning functionality), supporting binning in either time or phase-space, along with a live-preview that works in conjunction with changes to the underlying ephemeris (when phase-binning, the binning is recomputed with any change to the ephemeris that dictates that phase-folding).  Once loaded into the app, the binned data remain fixed (and with https://github.com/spacetelescope/jdaviz/pull/2312 would only be available to load in the respective viewer).
This PR currently only exposes the number of bins as an input parameter, but we might want to consider (now or as a follow-up effort) the ability to optionally provide a bin width in time/phase units instead.
Support for having live-updating binning in the data-collection …

binning plugin

---

lcviz/plugins/binning/binning.py
lcviz/plugins/binning/binning.vue
lcviz/tests/test_plugin_binning.py

This PR handles the case where the user empties the input for number of bins or sets it to an invalid value.  The live-preview now clears without a traceback and the "bin" button is disabled.  The input validation shows red text describing the reason the input is invalid (unchanged by this PR).

Binning: handle n_bins being empty or <= 0

---

lcviz/plugins/subset_plugin/subset_plugin.py

This enables support from ~https://github.com/spacetelescope/jdaviz/pull/2421~ https://github.com/spacetelescope/jdaviz/pull/2462 into lcviz's subset plugin.
https://github.com/spacetelescope/lcviz/assets/877591/83ca9d40-5a13-40ff-9675-5629c1db98e3
~This would require that PR to be merged (along with the necessary fixes for get_subsets and the subset plugin), but should not require it to be released in order to move forward with this PR.~
~This can be merged without jdaviz 3.7 released, but will require testing with jdaviz after that PR is merged (lcviz should work with _and_ without, but this feature will only be shown if you have jdaviz _with_ the upstream PR).~

enable subset freezing

---

lcviz/plugins/binning/binning.py
lcviz/plugins/flatten/flatten.py
lcviz/tests/test_plugin_flatten.py

this accompanies https://github.com/spacetelescope/jdaviz/pull/2386 and updates the flatten and binning plugins to make use of this new decorator, which should avoid any flickering for expensive cases.
This will require jdaviz 3.7 ~(once released - marking as draft until then)~.  ~The binning plugin from #28 will also require updates (either as part of that PR or this rebased on top of that once merged)~

update to use skip_if_no_updates_since_last_active

---

lcviz/events.py
lcviz/helper.py
lcviz/plugins/coords_info/coords_info.py
lcviz/plugins/ephemeris/ephemeris.py
lcviz/template_mixin.py
pyproject.toml

https://github.com/spacetelescope/jdaviz/pull/2338 implements viewer reference name updates in jdaviz, removing the need for that functionality in LCviz. 
This PR removes the duplicate code, and calls the jdaviz versions. This PR should not be merged until https://github.com/spacetelescope/jdaviz/pull/2338 is on main.
[🐱](https://jira.stsci.edu/browse/JDAT-3680)

Moving viewer reference renaming upstream to jdaviz

---

lcviz/utils.py

I wanted to make a demo with three Kepler quarters at short cadence, which contains 297,584 measurements. It was so slow that I was terribly sad. Here's a screen grab (before):
https://github.com/spacetelescope/lcviz/assets/3497584/530afdc9-070c-48e6-8d18-fc3d0bd40483
I executed `load_data` at 0:16, and the cell completes at 1:00 (44 seconds).
I found a silly and simple way to make it more performant. By default, the viewer will plot the first component in the `Data` as the x axis, and second component in y. On `main`, those are `dt` and `time`, which is not the correct y axis, of course. Late in the `viewer.add_data` process we call `set_plot_axes`, which switches to the correct axes. By starting off on the wrong foot, we have to wait for the data to be fully added before they are …

Swap component order to add data with correct axes on first go

---

lcviz/plugins/frequency_analysis/frequency_analysis.py

In Frequency Analysis, we plot the periodogram like so:
https://github.com/spacetelescope/lcviz/blob/b4bf32abef08242406b4c3e888f1249e0737ac95/lcviz/plugins/frequency_analysis/frequency_analysis.py#L172
Since the periodogram returns `Quantity`s for period and power, the traitlet can't successfully validate the array input, raising:
```
UserWarning: Given trait value dtype "float64" does not match required type "float64". A coerced copy has been created.
```
This PR extracts the `Quantity`s' values as ndarrays to avoid the warning.

Fix traitlet float64 warning

---

lcviz/plugins/binning/binning.py
lcviz/plugins/binning/binning.vue
lcviz/plugins/flatten/flatten.py
lcviz/plugins/flatten/flatten.vue

This PR introduces a check on the time that the live-updates take, and if exceeding a certain threshold, temporarily disables the live-preview updates and shows an alert prompting to either manually update the live-preview or disable the live-preview marks.
This also makes use of a [change upstream in jdaviz](https://github.com/spacetelescope/jdaviz/pull/2560) to show a spinner in the "apply" buttons when the plugin is computing which temporarily disables clicking the button.  For cases where binning/flattening is slow to run, this gives immediate feedback that the button was clicked and doesn't need to be clicked again.  This doesn't need to be blocked by pinning a new release of jdaviz, ~but should make sure that PR gets merged first~.
The code here can be simplified slightly by using …

flatten/binning: handle slow live-updates for large data

---

lcviz/plugins/ephemeris/ephemeris.py

as it says in the title, useful for notebook workflows, but just didn't want the diff buried in a notebook PR.

expose adopt_period_at_max_power through ephem API

---

lcviz/plugins/binning/binning.py
lcviz/plugins/frequency_analysis/frequency_analysis.py
lcviz/tests/test_plugin_frequency_analysis.py
pyproject.toml

This updates the plot in frequency analysis to account for changes upstream in https://github.com/spacetelescope/jdaviz/pull/2498 (which adds tool and pan/zoom support), and in doing so requires jdaviz 3.8.
Note that this also means that without this PR, the former implementation _may_ be broken once jdaviz 3.8 is released.
~**Waiting for:** jdaviz 3.8~

Use upstream updates to plugin plots

---

lcviz/helper.py

Supports https://github.com/spacetelescope/jdaviz/pull/2580 (without requiring to increase the pin).  Should not review/merge until that is merged.

future-proof for upstream changes to add additional css

---

pyproject.toml

This PR sets the min lightkurve version now that the upstream PR is actually released, instead of relying on referencing the latest on main directly.

set min lightkurve version

---

lcviz/plugins/binning/binning.py
lcviz/plugins/flatten/flatten.py

this updates #56 ~(and should be rebased once that is merged)~ to make use of the upstream implementation in https://github.com/spacetelescope/jdaviz/pull/2560, ~but is blocked by that upstream PR being merged, released, and the jdaviz pin updated here (otherwise the imports will fail).~
~**Waiting for:** jdaviz 3.8~

make use of with_spinner decorator

---

lcviz/plugins/plot_options/plot_options.py

This PR accompanies https://github.com/spacetelescope/jdaviz/pull/2449 and exposes the now-supported line traitlets through the plot options user API.
~**Waiting for:** jdaviz 3.8~

expose line traitlets through plot options user API

---

lcviz/tools.py

We override the export plot plugin, so need to point to the lcviz version in the toolbar shortcut.

fix target for export plot shortcut button

---

.github/workflows/ci_workflows.yml
.github/workflows/publish.yml
CHANGES.rst
lcviz/__init__.py
pyproject.toml

This PR enables `lcviz.test` and adapts the release workflow used in jdaviz.

Release workflow

---

lcviz/plugins/binning/binning.py

tests were occasionally failing because they relied on an exception in the live-update which sometimes did not trigger in time.

make check for n_bins more robust/performant

---

lcviz/plugins/ephemeris/ephemeris.py
lcviz/tests/test_plugin_ephemeris.py

This PR implements validation in ephemeris component naming to avoid breaking assumptions when parsing viewer names.
This won't do anything without the [upstream PR](https://github.com/spacetelescope/jdaviz/pull/2642), so the new tests have a condition to change behavior based on the version of jdaviz (which can then be removed in #68).
Eventually we might be able to remove this if/when we refactor the viewers to hold the information about their ephemeris, etc, within metadata instead of the label itself.  That would then allow us to set these labels by default, but allow the users to rename them without losing the ability to manage them from the plugins. [:cat:](https://jira.stsci.edu/browse/JDAT-4111)

ephemeris component validation

---

lcviz/parsers.py
lcviz/tests/test_parser.py
lcviz/utils.py
lcviz/viewers.py

Try it out with:
```python
import astropy.units as u
from astropy.time import Time
from lightkurve import search_lightcurve, search_targetpixelfile
tpf = search_targetpixelfile('KIC 6922244', author="Kepler", quarter=9, cadence="long").download()
lcviz = LCviz()
lcviz.load_data(tpf)
lcviz.show()
```

Adding TPF translator and parser

---

lcviz/parsers.py
lcviz/plugins/coords_info/coords_info.py
lcviz/viewers.py

This PR implements a dynamically-created TPF viewer.
* follow-up: re-enable clone viewer tool for TPF viewers [:cat:](https://jira.stsci.edu/browse/JDAT-4156)
Note that in order to get correct mouseover and stretch histogram, https://github.com/spacetelescope/jdaviz/pull/2678 is required (which is targeted for jdaviz 3.9).  Even with that, the default stretch percentile often drives the whole range, requiring using a custom stretch [:cat:](https://jira.stsci.edu/browse/JDAT-4155).  
Example case:
```
from lightkurve import search_lightcurve, search_targetpixelfile
lc = search_lightcurve("HAT-P-11", mission="Kepler", cadence="long", quarter=10).download() #.flatten()
tpf = search_targetpixelfile("HAT-P-11", mission="Kepler", cadence="long", quarter=10).download() …
```

TPF viewer

---

lcviz/plugins/coords_info/coords_info.py

This PR includes the exceptions needed by #81 that are now included in the lcviz code due to the refactor in https://github.com/spacetelescope/jdaviz/pull/2678

make use of upstream refactor to override indices in lcviz

---

lcviz/plugins/ephemeris/ephemeris.py

Previously, if a TPF was loaded before the phase-viewer was created, then the TPF data was loaded into the phase-viewer, resulting in a traceback.  Now when creating a phase-viewer, only 1D data are loaded into the viewer (with visibilities still defaulted based on the visibilities in the time viewer).

fix creating phase-viewer when TPF is loaded

---

CHANGES.rst
lcviz/plugins/ephemeris/ephemeris.py
lcviz/tests/test_plugin_binning.py
lcviz/tests/test_plugin_flatten.py
lcviz/tests/test_plugin_markers.py

Instead of exposing the entire viewer object when calling `ephem.create_phase_viewer()`, this instead exposes the user API introduced in https://github.com/spacetelescope/jdaviz/pull/2563 (already included in the existing jdaviz 3.8 pin).
This also adds support for passing floats through `ephem.times_to_phases`.

ephemeris plugin: phase viewer user API and float support for times_to_phases

---

CHANGES.rst
lcviz/plugins/ephemeris/ephemeris.py
lcviz/tests/test_plugin_ephemeris.py

Previously cloned phase-viewers (introduced in #74, not yet in a release) were not updated (renamed or removed) when an ephemeris component was renamed.  This PR updates the ephemeris plugin to be aware that there may be multiple phase-viewers corresponding to the ephemeris, and treats the "first" as the default when assigning defaults based on axes limits, etc.
(ignore the crashing time plot - too many notebooks running at once)
https://github.com/spacetelescope/lcviz/assets/877591/70eb135a-3562-49c9-9884-ed38e9e30991
devdeps failure is likely because of jdaviz, but we are still pinned to jdaviz 3.8 (and those tests are passing).  See #92 and #68.

Fix cloned phase-viewers when deleting/renaming an ephemeris component

---

CHANGES.rst
lcviz/helper.py
lcviz/parsers.py
lcviz/plugins/__init__.py
lcviz/plugins/binning/binning.py
lcviz/plugins/ephemeris/ephemeris.py
lcviz/plugins/flatten/flatten.py
lcviz/plugins/viewer_creator/__init__.py
lcviz/plugins/viewer_creator/viewer_creator.py
lcviz/tests/test_parser.py
lcviz/tests/test_plugin_binning.py
lcviz/tests/test_plugin_ephemeris.py
lcviz/tests/test_plugin_flatten.py
lcviz/tests/test_plugin_frequency_analysis.py
lcviz/tests/test_plugin_markers.py
lcviz/tests/test_translator.py
lcviz/tests/test_tray_viewer_creator.py
lcviz/tests/test_viewers.py
lcviz/viewers.py

**NOTE**: this should be tested with jdaviz 3.8.x since this does not include updates for jdaviz 3.9 covered in #68.
This adds a viewer creator dropdown in the app-level toolbar which can create viewers, including phase viewers attached to a specific ephemeris.
https://github.com/spacetelescope/lcviz/assets/877591/c29ab69a-c3d6-4305-b860-d8ff484b864f
~The current behavior is to first check for an existing viewer with a matching label and if it exists, _clone_ the existing viewer (keeping data visibilities and plot options, etc), and otherwise create a new viewer.~
TODO:
Once merged:
The styling will also be improved by upstream https://github.com/spacetelescope/jdaviz/pull/2743

Viewer creator in app toolbar

---

pyproject.toml
tox.ini

We're currently pinning a minor version of jdaviz and handling updates manually, so want to test that version of jdaviz with other devdeps (so a break caused by jdaviz does not prevent us from testing the other devdeps).  Updating the pin to the next minor version of jdaviz is currently handled by PRs that bump the version and apply any necessary changes (i.e. #68) which will then ensure tests pass before bumping the minor version of jdaviz.
If we ever stop tagging a specific minor version, dev tests for jdaviz should be re-introduced (as mentioned in the added comment in `pyproject.toml`)

temporarily remove jdaviz from devdeps

---

pyproject.toml

with glue >= 1.19.0, we are getting the following traceback when loading data:
```
../../.tox/py310-test-alldeps-cov/lib/python3.10/site-packages/glue/viewers/image/state.py:607: in _update_attribute_display_unit_choices
self.attribute_display_unit = component.units
../../.tox/py310-test-alldeps-cov/lib/python3.10/site-packages/echo/core.py:263: in __setattr__
self._notify_global(**{attribute: value})
../../.tox/py310-test-alldeps-cov/lib/python3.10/site-packages/glue/utils/matplotlib.py:170: in wrapper
return func(*args, **kwargs)
../../.tox/py310-test-alldeps-cov/lib/python3.10/site-packages/glue/viewers/matplotlib/state.py:319: in _notify_global
super(MatplotlibLayerState, self)._notify_global(*args, **kwargs)
../../.tox/py310-test-alldeps-cov/lib/python3.10/site-packages/echo/core.py:2 …
```

temporarily avoid conflicts introduced by recent glue releases

---

lcviz/parsers.py

rather than an internal error that light_curve is not defined.
To reproduce:
```
lcviz = LCviz()
lcviz.load_data(None)
```

raise error when parser can't identify file_obj

---

CHANGES.rst
lcviz/plugins/metadata_viewer/metadata_viewer.py

This PR closes #88 by monkeypatching the string representation of `astropy.io.fits.card.Undefined` to show an empty string in the metadata plugin instead of something like `<astropy.io.fits.card.Undefined object at 0x29f5b94d0>`

metadata: monkeypatch Undefined to show as empty string

---

CHANGES.rst
lcviz/parsers.py

This PR modifies the default data_labels for light curves to _remove_ flux-origin (since that can now be changed later by the flux origin plugin) and _adds_ quarter/campaign/sector information.
Note that calling `stitch` before loading into lcviz, will result in the _last_ quarter/campaign/sector being adopted in the metadata and therefore into the data-label.  Is this something we should propose for changes upstream?
Also note: TPF data are still suffixed with `[TPF]` in this PR, although that could be changed now or in the future if desired.
Discussion points:

replace flux-origin with quarter/campaign/sector in data_label

---

lcviz/plugins/coords_info/coords_info.py
lcviz/plugins/markers/markers.py
lcviz/tests/test_plugin_markers.py

This PR adds full mouseover information and marker plugin support for the TPF viewer.

TPF viewer: marker/mouseover support

---

docs/plugins.rst
lcviz/helper.py
lcviz/plugins/__init__.py
lcviz/plugins/stitch/__init__.py
lcviz/plugins/stitch/stitch.py
lcviz/plugins/stitch/stitch.vue
lcviz/tests/test_plugin_stitch.py

https://github.com/spacetelescope/lcviz/assets/877591/e2a8b571-e8ab-41b2-a163-162eaf0f719a
[Stitch plugins docs](https://lcviz--107.org.readthedocs.build/en/107/plugins.html#stitch)
Potential follow-up:
* normalize/flatten capabilities or custom user-provided `corrector_func`. 
See https://docs.lightkurve.org/reference/api/lightkurve.LightCurveCollection.stitch.html
Open questions:

Stitch plugin

---

lcviz/tests/test_plugin_stitch.py

by ensuring the data is loaded in a viewer before checking if the stitch plugin is active

make stitch test more robust

---

CHANGES.rst
lcviz/parsers.py
lcviz/plugins/plot_options/plot_options.py

This PR gives a better default colormap stretch on TPF files. It sets vmin/vmax to the 5/99 percentile limits from the cube:
```python
from lightkurve import search_targetpixelfile, search_lightcurve
target = 'TRAPPIST-1'
lc = search_lightcurve(target, mission="K2", cadence="long").download().normalize()
tpf = search_targetpixelfile(target, mission="K2", cadence="long").download()
lcviz = LCviz()
lcviz.load_data(lc)
lcviz.load_data(tpf)
lcviz.show()
viewer = lcviz.app.get_viewer('flux-vs-time')
viewer.state.y_min = 0.9
viewer.state.y_max = 1.2
```
I opted to put this stretch as a private method in `PlotOptions`, and call the method from the parser when a TPF is loaded. That keeps the diff small. Caveats: this approach won't work if we load more than one TPF into …

Better default TPF stretch

---

CHANGES.rst
lcviz/plugins/binning/binning.py
lcviz/plugins/ephemeris/ephemeris.py
lcviz/plugins/flatten/flatten.py
lcviz/plugins/flux_column/flux_column.py
lcviz/plugins/frequency_analysis/frequency_analysis.py
lcviz/plugins/stitch/stitch.py
lcviz/utils.py

all plugins that expect light curves as input should now (as of #82 which is not included in 0.3.x) filter to exclude TPFs.

exclude TPF from plugins that expect lcs as input

---

.github/workflows/ci_workflows.yml
.github/workflows/publish.yml
CHANGES.rst
docs/installation.rst
lcviz/helper.py
lcviz/plugins/coords_info/coords_info.py
lcviz/plugins/time_selector/time_selector.py
lcviz/tests/test_plugin_markers.py
lcviz/viewers.py
pyproject.toml

* Updates to handle changes in https://github.com/spacetelescope/jdaviz/pull/2758
* Requires https://github.com/spacetelescope/jdaviz/pull/2895 (will be included in 3.10.2)
**TODO**:
**Waiting for**: jdaviz 3.10.2 (update pin in pyproject once released)
Closes #110

jdaviz 3.10 updates

---

CHANGES.rst
lcviz/conftest.py
lcviz/parsers.py
lcviz/tests/test_parser.py
lcviz/tests/test_plugin_markers.py
lcviz/tests/test_plugin_stitch.py
pyproject.toml

If you load Kepler data from Quarter 10 with a `data_label = "Target in Q10"`, the parser will happily add another "Q10" to the end of the data label [🐱](https://jira.stsci.edu/browse/JDAT-4565). This PR checks if the sub-interval for any mission is already in the data label, and only adds one if none is found.

Prevent duplicate sub-interval data labels

---

CHANGES.rst
lcviz/utils.py

which affected CDIPS HLSP light curves and prevented them from being loaded into lcviz.  Note that the time format is still incorrect, but that is a separate issue.

fix CDIPS parsing support (column filled with strings)

---

CHANGES.rst
pyproject.toml

Was included in #120, but never backported.

(temporarily) max pin numpy<2

---

CHANGES.rst
lcviz/helper.py
lcviz/plugins/export/export.py
lcviz/plugins/markers/markers.py
lcviz/plugins/metadata_viewer/metadata_viewer.py
lcviz/plugins/plot_options/plot_options.py
lcviz/plugins/subset_plugin/subset_plugin.py
lcviz/plugins/time_selector/time_selector.py

This PR ensures that all internal docs links buttons point to the correct version on RTD, and don't use the upstream version tag set by jdaviz.

Use lcviz version in all docs links

---

CHANGES.rst
lcviz/conftest.py
lcviz/plugins/ephemeris/ephemeris.py
lcviz/plugins/ephemeris/ephemeris.vue
lcviz/tests/test_parser.py
lcviz/tests/test_plugin_ephemeris.py
lcviz/tests/test_plugin_markers.py

```python
from lightkurve import search_lightcurve
lc = search_lightcurve(
"TRAPPIST-1", mission='K2', author='EVEREST'
)[0].download().remove_nans().normalize().remove_outliers()
lcviz = LCviz()
lcviz.load_data(lc)
lcviz.show()
flatten = lcviz.plugins['Flatten']
flatten.window_length = 31
flatten.flatten();
ephem = lcviz.plugins['Ephemeris']
ephem.query_for_ephemeris()
for planet in ephem.query_result.choices[:3]:
ephem.query_result = planet
ephem.adopt_from_catalog_in_new_viewer()
```

Add methods for querying NASA Exoplanet Archive for ephemeris

---

docs/reference/api_plugins.rst

Rendered plugins page (all links from API examples should now be working): https://lcviz--134.org.readthedocs.build/en/134/plugins.html

FIX: add missing plugin API docs entries

---

CHANGES.rst
lcviz/plugins/coords_info/coords_info.py
lcviz/viewers.py

This along with https://github.com/glue-viz/glue-jupyter/pull/467 (included in glue-jupyter 0.22.2) improves the performance at load time, especially when the server is remote.
Note that lcviz does not explicitly pin glue-jupyter (it pulls in glue-jupyter through jdaviz).

improve initial scatter/mouseover performance

---

CHANGES.rst
pyproject.toml

This pins glue-jupyter to 0.22.2+ (the pinned jdaviz only requires 0.22.1+) to ensure https://github.com/glue-viz/glue-jupyter/pull/467 is included.

pin glue-jupyter to 0.22.2+

---

docs/conf.py

see https://github.com/lightkurve/lightkurve/issues/1466
if/when the original location is fixed, we can revert this.

(temporary) update of lightkurve docs location

---

CHANGES.rst
pyproject.toml

Should close #116 (as jdaviz 4.0 no longer requires voila)
**Waiting for**: ~jdaviz 4.0~

jdaviz 4.0 updates

---

.github/workflows/check_changelog.yml
.github/workflows/check_milestone.yml
.github/workflows/ci_cron_weekly.yml
.github/workflows/ci_workflows.yml
.github/workflows/publish.yml

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)

MNT: Use hash for Action workflow versions and update if needed

---

pyproject.toml

Since https://github.com/spacetelescope/jdaviz/pull/3317, `jdaviz` ignores a warning raised by `mpl_scatter_density` (https://github.com/astrofrog/mpl-scatter-density/issues/46, https://github.com/astrofrog/mpl-scatter-density/pull/47). We should use the same ignore in lcviz until the upstream fix is released.

Ignore mpl_scatter_density warning temporarily

---

CHANGES.rst
lcviz/components/components.py
lcviz/helper.py
lcviz/parsers.py

By default, this will load each TCE extension into the data collection as a separate object and display them all. Specifying `extname` will skip adding the deselected extensions into viewers. Opening as draft since I need to fix the auto-generated data label. I probably also need to think a little harder about what to do with the ephemeris in the case of multiple TCE extensions that are all added to the viewer.

Add parser for TESS DVT files

---

.github/workflows/publish.yml
CHANGES.rst
lcviz/__init__.py

Remove astropy test runner

---

lcviz/viewers.py

The reference viewer x-axis is set by `TimeScatterView._set_plot_x_axes`, which currently requires that you pass in a `LightCurve` with a reference time in the `meta` attribute. The function already requires you to pass a `DataCollection`, which should also have at least one entry with a reference time on its `TimeCoordinate`.
This PR allows you to set the x-axis without a `LightCurve`, which is useful if you want to change the axes for an already-loaded light curve in the data collection.

Extract reference time from data collection

---

docs/index.rst

docs.lightkurve.org is the old link, which is now broken -- this updates to the latest link

fix link to lightkurve docs

---

CHANGES.rst
lcviz/components/plugin_ephemeris_select.vue
lcviz/plugins/binning/binning.vue

This PR adds the API hint for `lcviz.plugins['Binnning'].ephemeris`.

add missing api-hint for binning.ephemeris

---

CHANGES.rst
lcviz/plugins/stitch/stitch.py
lcviz/tests/test_plugin_stitch.py

Jdaviz no longer has an `app.vue_data_item_remove` method, so this needed to be updated to use the backend method.

Fix stitch data removal with Jdaviz 4.2

---

CHANGES.rst
lcviz/helper.py

This PR allows files to be parsed where `TELESCOP` is not set.

parser: do not require TELESCOP to be set

---

CHANGES.rst
lcviz/plugins/ephemeris/ephemeris.py

This PR fixes the case of setting original phase-viewer limits of a non-selected ephemeris component

fix bug in setting wrap_at of non-active ephem component

---

CHANGES.rst
lcviz/parsers.py
lcviz/plugins/binning/binning.py
lcviz/tests/test_plugin_binning.py
pyproject.toml

A new glue translator for `astropy.table.Table` was recently added by a PR from @rosteen, https://github.com/glue-viz/glue-astronomy/pull/103. The `Table` handler is getting returned via `data_translator.get_handler_for` because `isinstance(LightCurve(), Table) == True`, even though we really need to check `expected_cls is target_cls`. 
This PR calls the `LightCurveHandler` directly to workaround the registry misfire while we sort that out with Tom.
The relevant bit of the glue translator logic is here: https://github.com/glue-viz/glue/blob/bf65166f1f8a4367d4b43195a38e4ff653385d6b/glue/config.py#L514

Fix for translating light curves as LightCurve objects rather than Tables

---

CHANGES.rst
lcviz/loaders/importers/lightcurve/lightcurve.py
lcviz/loaders/importers/lightcurve/lightcurve.vue
lcviz/loaders/importers/tpf/tpf.py
pyproject.toml

This PR updates lcviz to be compatible with jdaviz 4.4, including support for selecting/naming the viewer within the loaders as well as improvements to the logger.
**Waiting for**:

jdaviz 4.4 updates
